name: Run tests

on:
  push:

jobs:
  tests:
    name: Run the tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install npm
        uses: actions/setup-node@v4

      - name: Install tools
        run: |
          npm install -g bats

      - name: Run tests
        run: |
          make test
